insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (1, 'Ignition Module 12V', 'Heavy-duty industrial grade', 629.38, 95, 3, 241);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (2, 'Thermostat 2HP', 'High-quality aftermarket part', 1971.3, 91, 9, 182);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (3, 'Thermostat 12V', 'Commercial-grade component', 19.63, 54, 15, 139);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (4, 'O-Ring Set XL', 'Energy-efficient model', 521.52, 78, 7, 389);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (5, 'Seal Kit 200mm', 'Heavy-duty industrial grade', 1976.1, 71, 5, 381);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (6, 'Float Switch 12V', 'Commercial-grade component', 1414.09, 30, 4, 461);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (7, 'Latch Assembly Mini', 'Heavy-duty industrial grade', 604.79, 9, 5, 271);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (8, 'Door Gasket 5kW', 'Heavy-duty industrial grade', 266.57, 74, 7, 42);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (9, 'Defrost Heater 2HP', 'Precision-engineered replacement', 979.56, 4, 2, 484);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (10, 'Water Inlet Valve 24V', 'High-quality aftermarket part', 1502.73, 4, 9, 258);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (11, 'Handle Assembly 200mm', 'Food-safe certified', 802.97, 97, 11, 300);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (12, 'Spray Arm 12V', 'Universal fit component', 1668.35, 49, 8, 21);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (13, 'Handle Assembly 200mm', 'Commercial-grade component', 1809.47, 77, 12, 192);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (14, 'Guard Cover 12V', 'Food-safe certified', 832.63, 17, 14, 405);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (15, 'Float Switch XL', 'Heavy-duty industrial grade', 1771.56, 5, 5, 395);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (16, 'Burner Assembly 5kW', 'Stainless steel construction', 1616.32, 9, 8, 73);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (17, 'Latch Assembly 120mm', 'Precision-engineered replacement', 647.62, 42, 14, 32);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (18, 'Defrost Heater 24V', 'OEM replacement part', 1617.76, 91, 11, 180);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (19, 'Clamp 5kW', 'Stainless steel construction', 415.25, 6, 3, 243);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (20, 'Spring Kit 1HP', 'OEM replacement part', 1360.66, 13, 2, 227);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (21, 'Spring Kit XL', 'Energy-efficient model', 454.96, 27, 15, 12);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (22, 'Water Inlet Valve XL', 'Universal fit component', 471.24, 13, 14, 82);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (23, 'Grate 24V', 'Precision-engineered replacement', 136.73, 90, 2, 101);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (24, 'Vibration Pad Standard', 'Stainless steel construction', 796.96, 66, 6, 482);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (25, 'Belt Drive 3kW', 'Food-safe certified', 802.81, 44, 2, 399);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (26, 'Hinge Pin 200mm', 'Food-safe certified', 191.36, 75, 13, 309);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (27, 'Exhaust Duct 1HP', 'Commercial-grade component', 1399.0, 58, 3, 267);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (28, 'Grate 200mm', 'Universal fit component', 1851.28, 45, 12, 61);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (29, 'Grease Trap Mini', 'High-quality aftermarket part', 572.71, 60, 12, 101);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (30, 'Ice Mold 120mm', 'Precision-engineered replacement', 444.64, 51, 12, 232);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (31, 'Temperature Sensor 1HP', 'Commercial-grade component', 47.29, 41, 6, 419);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (32, 'Capacitor 2HP', 'Commercial-grade component', 158.31, 31, 3, 414);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (33, 'Grate 12V', 'Commercial-grade component', 1616.77, 68, 4, 32);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (34, 'Relay Module 12V', 'Food-safe certified', 617.04, 20, 15, 452);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (35, 'Power Cord 200mm', 'Commercial-grade component', 427.29, 50, 10, 180);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (36, 'Pressure Switch Pro', 'Heavy-duty industrial grade', 67.22, 72, 8, 209);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (37, 'Condenser Coil 120mm', 'NSF-approved component', 706.15, 13, 9, 324);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (38, 'Drain Valve 12V', 'Heavy-duty industrial grade', 1132.4, 74, 8, 199);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (39, 'Relay Module Mini', 'Heavy-duty industrial grade', 1319.15, 5, 5, 220);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (40, 'Timer XL', 'OEM replacement part', 1881.18, 58, 3, 388);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (41, 'Guard Cover 120mm', 'High-quality aftermarket part', 712.98, 9, 8, 353);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (42, 'Handle Assembly 200mm', 'Food-safe certified', 1194.34, 100, 6, 340);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (43, 'Compressor Motor 12V', 'Commercial-grade component', 1569.76, 19, 12, 2);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (44, 'Circuit Breaker XL', 'High-quality aftermarket part', 1542.13, 29, 11, 404);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (45, 'Float Switch 3kW', 'High-quality aftermarket part', 1078.53, 30, 14, 214);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (46, 'Agitator Pro', 'NSF-approved component', 1358.37, 43, 15, 263);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (47, 'Bearing Assembly Standard', 'Precision-engineered replacement', 1838.49, 47, 5, 288);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (48, 'Mounting Bracket 5kW', 'Precision-engineered replacement', 999.94, 70, 9, 89);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (49, 'Gas Valve Mini', 'Energy-efficient model', 1961.32, 52, 3, 88);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (50, 'Contactor Standard', 'Heavy-duty industrial grade', 1318.17, 72, 13, 160);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (51, 'Door Gasket 120mm', 'High-quality aftermarket part', 808.44, 7, 8, 270);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (52, 'Clamp 3kW', 'Energy-efficient model', 540.6, 98, 15, 471);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (53, 'Blade Assembly 5kW', 'OEM replacement part', 1585.4, 88, 7, 84);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (54, 'Blade Assembly 1HP', 'Stainless steel construction', 663.0, 80, 13, 141);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (55, 'Vibration Pad 3kW', 'OEM replacement part', 1620.85, 14, 9, 4);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (56, 'Fuse 1HP', 'Universal fit component', 1197.06, 71, 14, 47);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (57, 'Belt Drive 5kW', 'Precision-engineered replacement', 1241.14, 5, 14, 235);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (58, 'Control Board 24V', 'OEM replacement part', 234.3, 86, 15, 5);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (59, 'Exhaust Duct 3kW', 'NSF-approved component', 1735.77, 58, 2, 103);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (60, 'Seal Kit Mini', 'Energy-efficient model', 1188.25, 45, 9, 71);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (61, 'Relay Module 12V', 'High-quality aftermarket part', 707.04, 98, 5, 97);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (62, 'Contactor 24V', 'Heavy-duty industrial grade', 1713.39, 100, 5, 130);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (63, 'Expansion Valve 200mm', 'Universal fit component', 1968.65, 39, 12, 305);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (64, 'Clamp 120mm', 'Universal fit component', 957.37, 89, 15, 461);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (65, 'Mounting Bracket Standard', 'Heavy-duty industrial grade', 1215.21, 75, 6, 258);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (66, 'Drain Valve 3kW', 'High-quality aftermarket part', 1834.53, 49, 7, 408);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (67, 'Solenoid Valve Standard', 'Stainless steel construction', 1053.95, 61, 9, 450);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (68, 'Heating Element 5kW', 'Commercial-grade component', 878.97, 35, 4, 110);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (69, 'Compressor Motor 5kW', 'Food-safe certified', 1195.22, 31, 14, 426);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (70, 'Pressure Switch 2HP', 'Food-safe certified', 1956.0, 50, 14, 419);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (71, 'Bearing Assembly 2HP', 'Precision-engineered replacement', 1367.48, 19, 10, 37);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (72, 'Latch Assembly XL', 'Universal fit component', 733.7, 89, 13, 431);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (73, 'Filter Cartridge 120mm', 'Food-safe certified', 1093.88, 99, 14, 414);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (74, 'Expansion Valve 120mm', 'Energy-efficient model', 1136.05, 25, 9, 343);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (75, 'Agitator Pro', 'Stainless steel construction', 301.39, 57, 4, 58);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (76, 'Drain Valve XL', 'Stainless steel construction', 992.6, 73, 2, 98);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (77, 'Water Inlet Valve 12V', 'NSF-approved component', 1640.42, 7, 14, 295);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (78, 'Seal Kit 2HP', 'Energy-efficient model', 13.36, 72, 6, 342);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (79, 'Pressure Switch 1HP', 'Heavy-duty industrial grade', 1950.58, 54, 9, 320);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (80, 'Float Switch 1HP', 'OEM replacement part', 1225.86, 37, 4, 274);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (81, 'Hinge Pin Mini', 'Energy-efficient model', 923.74, 43, 6, 59);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (82, 'Door Gasket 120mm', 'Stainless steel construction', 1031.36, 13, 15, 383);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (83, 'Fuse Mini', 'High-quality aftermarket part', 1479.32, 40, 12, 31);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (84, 'Power Cord 5kW', 'OEM replacement part', 988.6, 83, 10, 181);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (85, 'Hinge Pin 120mm', 'Universal fit component', 949.76, 21, 3, 362);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (86, 'Temperature Sensor Standard', 'Precision-engineered replacement', 1862.74, 74, 11, 54);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (87, 'Drip Tray Mini', 'Food-safe certified', 1637.66, 78, 6, 218);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (88, 'Filter Cartridge Standard', 'Universal fit component', 698.26, 56, 9, 430);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (89, 'Grease Trap 1HP', 'OEM replacement part', 342.69, 30, 2, 33);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (90, 'Spring Kit 3kW', 'Precision-engineered replacement', 702.03, 80, 12, 71);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (91, 'Control Board 3kW', 'Food-safe certified', 67.78, 66, 13, 4);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (92, 'Vibration Pad Mini', 'Food-safe certified', 1712.82, 4, 3, 374);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (93, 'Handle Assembly 12V', 'Energy-efficient model', 509.93, 52, 7, 220);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (94, 'Spring Kit 5kW', 'Energy-efficient model', 327.24, 3, 13, 78);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (95, 'Ignition Module 5kW', 'Universal fit component', 794.65, 84, 2, 259);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (96, 'Expansion Valve 2HP', 'OEM replacement part', 758.38, 60, 4, 202);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (97, 'Vibration Pad 200mm', 'Precision-engineered replacement', 1672.8, 23, 12, 409);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (98, 'Water Inlet Valve Standard', 'Heavy-duty industrial grade', 1419.79, 24, 15, 266);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (99, 'Circuit Breaker 12V', 'High-quality aftermarket part', 860.39, 70, 5, 244);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (100, 'Fan Motor XL', 'Heavy-duty industrial grade', 1199.4, 21, 2, 145);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (101, 'Gas Valve 5kW', 'Commercial-grade component', 1415.78, 41, 11, 280);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (102, 'Fuse 2HP', 'Commercial-grade component', 945.44, 34, 14, 376);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (103, 'Gas Valve 1HP', 'Precision-engineered replacement', 39.99, 11, 13, 493);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (104, 'Water Pump XL', 'Energy-efficient model', 1591.39, 67, 15, 478);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (105, 'Seal Kit 12V', 'NSF-approved component', 1638.49, 10, 3, 293);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (106, 'Water Inlet Valve 3kW', 'Commercial-grade component', 857.58, 31, 5, 400);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (107, 'Circuit Breaker 200mm', 'High-quality aftermarket part', 668.21, 49, 10, 72);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (108, 'Pressure Switch 200mm', 'High-quality aftermarket part', 864.21, 99, 13, 417);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (109, 'Water Pump 200mm', 'Universal fit component', 961.28, 42, 4, 413);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (110, 'Thermostat Standard', 'Heavy-duty industrial grade', 743.33, 80, 6, 339);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (111, 'Seal Kit 2HP', 'Commercial-grade component', 1291.63, 25, 5, 160);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (112, 'Condenser Coil Mini', 'High-quality aftermarket part', 423.75, 95, 2, 498);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (113, 'Water Inlet Valve 24V', 'OEM replacement part', 751.46, 91, 7, 495);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (114, 'Grate 200mm', 'High-quality aftermarket part', 914.53, 60, 15, 246);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (115, 'Defrost Heater 2HP', 'High-quality aftermarket part', 170.44, 3, 4, 370);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (116, 'Condenser Coil 1HP', 'Universal fit component', 582.55, 10, 12, 25);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (117, 'Power Cord XL', 'Heavy-duty industrial grade', 905.59, 76, 14, 369);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (118, 'Pilot Assembly XL', 'Precision-engineered replacement', 112.75, 66, 10, 193);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (119, 'Water Inlet Valve 3kW', 'OEM replacement part', 243.8, 83, 6, 221);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (120, 'Circuit Breaker 1HP', 'Energy-efficient model', 259.14, 3, 2, 199);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (121, 'Pilot Assembly 3kW', 'Universal fit component', 648.73, 18, 11, 188);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (122, 'Thermostat 12V', 'NSF-approved component', 483.42, 47, 10, 107);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (123, 'Power Cord Pro', 'Food-safe certified', 1184.95, 69, 9, 25);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (124, 'Latch Assembly Standard', 'Precision-engineered replacement', 1240.58, 16, 3, 183);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (125, 'Timer 24V', 'Food-safe certified', 1510.79, 43, 11, 421);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (126, 'Guard Cover XL', 'Commercial-grade component', 258.83, 11, 14, 240);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (127, 'Power Cord 1HP', 'Stainless steel construction', 942.81, 69, 6, 367);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (128, 'Timer 3kW', 'Stainless steel construction', 584.34, 74, 5, 472);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (129, 'Thermostat 120mm', 'OEM replacement part', 305.87, 58, 14, 395);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (130, 'Heating Element 120mm', 'Food-safe certified', 685.53, 4, 10, 133);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (131, 'Drain Valve 12V', 'Universal fit component', 1671.2, 90, 4, 14);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (132, 'Capacitor 24V', 'Food-safe certified', 219.45, 13, 13, 452);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (133, 'Heating Element 200mm', 'Precision-engineered replacement', 584.72, 38, 3, 148);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (134, 'Handle Assembly 3kW', 'Food-safe certified', 1541.22, 18, 9, 306);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (135, 'Solenoid Valve 24V', 'Commercial-grade component', 1831.03, 40, 12, 359);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (136, 'Latch Assembly Standard', 'NSF-approved component', 1723.16, 80, 4, 39);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (137, 'Water Inlet Valve 120mm', 'Stainless steel construction', 1923.74, 7, 8, 42);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (138, 'Guard Cover 1HP', 'Heavy-duty industrial grade', 1314.69, 87, 2, 319);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (139, 'Control Board XL', 'NSF-approved component', 871.35, 89, 14, 446);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (140, 'Pilot Assembly Standard', 'NSF-approved component', 1275.81, 29, 11, 9);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (141, 'Evaporator Coil 12V', 'High-quality aftermarket part', 693.55, 7, 8, 193);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (142, 'Water Inlet Valve 5kW', 'Universal fit component', 141.3, 23, 4, 12);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (143, 'Guard Cover XL', 'Energy-efficient model', 826.63, 84, 3, 268);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (144, 'Guard Cover 5kW', 'Stainless steel construction', 170.47, 64, 12, 443);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (145, 'Vibration Pad XL', 'Universal fit component', 1232.99, 56, 8, 125);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (146, 'Circuit Breaker 2HP', 'NSF-approved component', 1250.82, 47, 2, 366);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (147, 'Grease Trap Pro', 'Energy-efficient model', 279.95, 1, 9, 372);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (148, 'Burner Assembly 12V', 'NSF-approved component', 417.47, 84, 8, 227);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (149, 'Drip Tray 2HP', 'High-quality aftermarket part', 1476.98, 7, 13, 296);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (150, 'Latch Assembly XL', 'Heavy-duty industrial grade', 68.59, 84, 6, 216);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (151, 'Heating Element 1HP', 'NSF-approved component', 900.52, 63, 7, 318);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (152, 'Fuse 5kW', 'Universal fit component', 1454.64, 81, 6, 16);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (153, 'Door Gasket 24V', 'Stainless steel construction', 1673.94, 93, 9, 80);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (154, 'Door Gasket 2HP', 'NSF-approved component', 33.52, 79, 11, 331);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (155, 'Bearing Assembly 3kW', 'Food-safe certified', 1426.97, 72, 3, 270);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (156, 'Exhaust Duct 200mm', 'High-quality aftermarket part', 251.23, 92, 9, 357);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (157, 'Circuit Breaker 120mm', 'OEM replacement part', 122.74, 67, 5, 159);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (158, 'Circuit Breaker 120mm', 'Commercial-grade component', 702.32, 65, 8, 259);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (159, 'Pilot Assembly 200mm', 'Commercial-grade component', 54.14, 78, 8, 148);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (160, 'Float Switch XL', 'High-quality aftermarket part', 1210.91, 73, 11, 333);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (161, 'Door Gasket Standard', 'Energy-efficient model', 1880.48, 6, 8, 25);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (162, 'Belt Drive Mini', 'Food-safe certified', 1799.1, 63, 7, 254);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (163, 'Door Gasket 3kW', 'Heavy-duty industrial grade', 981.02, 83, 2, 114);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (164, 'Condenser Coil XL', 'Precision-engineered replacement', 1309.09, 74, 7, 393);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (165, 'Bearing Assembly Pro', 'Stainless steel construction', 1379.13, 89, 3, 319);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (166, 'Clamp Mini', 'Commercial-grade component', 609.72, 98, 8, 332);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (167, 'Relay Module 2HP', 'Heavy-duty industrial grade', 777.78, 71, 13, 351);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (168, 'Drip Tray 200mm', 'High-quality aftermarket part', 1092.66, 94, 2, 246);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (169, 'Timer Standard', 'Universal fit component', 1252.81, 40, 5, 476);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (170, 'Burner Assembly 24V', 'OEM replacement part', 671.12, 22, 14, 92);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (171, 'Solenoid Valve Standard', 'Universal fit component', 382.5, 65, 9, 199);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (172, 'Gas Valve 200mm', 'Food-safe certified', 163.14, 7, 2, 53);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (173, 'Pressure Switch 1HP', 'NSF-approved component', 1363.62, 24, 6, 21);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (174, 'Control Board 5kW', 'Food-safe certified', 599.37, 77, 10, 55);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (175, 'Filter Cartridge Standard', 'Food-safe certified', 1771.9, 73, 9, 25);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (176, 'Drip Tray 12V', 'Energy-efficient model', 655.99, 2, 8, 438);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (177, 'Hinge Pin 5kW', 'OEM replacement part', 491.22, 94, 15, 370);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (178, 'Fuse 3kW', 'Food-safe certified', 948.69, 43, 10, 491);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (179, 'Belt Drive Standard', 'Heavy-duty industrial grade', 240.04, 10, 9, 332);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (180, 'Control Board XL', 'Food-safe certified', 1759.66, 42, 8, 61);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (181, 'Filter Cartridge 3kW', 'Universal fit component', 1868.28, 49, 6, 426);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (182, 'Pilot Assembly 12V', 'Heavy-duty industrial grade', 345.09, 59, 2, 95);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (183, 'Drain Valve 1HP', 'Energy-efficient model', 1165.67, 96, 2, 126);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (184, 'Exhaust Duct Mini', 'Precision-engineered replacement', 1147.69, 42, 12, 350);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (185, 'Mounting Bracket Pro', 'High-quality aftermarket part', 1599.09, 0, 8, 286);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (186, 'Agitator 200mm', 'Precision-engineered replacement', 772.06, 92, 10, 318);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (187, 'Latch Assembly Standard', 'Energy-efficient model', 1025.36, 17, 3, 289);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (188, 'Handle Assembly 2HP', 'Commercial-grade component', 710.99, 65, 4, 334);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (189, 'Defrost Heater Pro', 'NSF-approved component', 1275.63, 82, 11, 28);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (190, 'Capacitor 24V', 'OEM replacement part', 1837.89, 35, 8, 113);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (191, 'Grease Trap Standard', 'OEM replacement part', 122.5, 85, 4, 214);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (192, 'Water Pump Pro', 'Commercial-grade component', 1933.33, 12, 2, 50);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (193, 'Spray Arm Mini', 'Heavy-duty industrial grade', 282.11, 42, 4, 424);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (194, 'Evaporator Coil Standard', 'Commercial-grade component', 1489.89, 8, 3, 153);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (195, 'Compressor Motor 12V', 'Commercial-grade component', 1365.02, 85, 15, 289);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (196, 'Fan Motor 12V', 'High-quality aftermarket part', 1964.65, 90, 8, 49);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (197, 'Belt Drive Pro', 'Stainless steel construction', 461.16, 27, 12, 417);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (198, 'Spray Arm 3kW', 'Stainless steel construction', 382.72, 44, 4, 221);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (199, 'Handle Assembly 3kW', 'Energy-efficient model', 1129.47, 3, 8, 97);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (200, 'Contactor 2HP', 'Stainless steel construction', 740.19, 96, 2, 371);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (201, 'Capacitor 120mm', 'Stainless steel construction', 862.92, 11, 4, 151);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (202, 'Grease Trap 1HP', 'Food-safe certified', 199.0, 9, 3, 223);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (203, 'Handle Assembly 24V', 'Heavy-duty industrial grade', 372.35, 46, 2, 13);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (204, 'Defrost Heater Mini', 'Precision-engineered replacement', 455.26, 72, 15, 12);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (205, 'Hinge Pin 12V', 'OEM replacement part', 1387.96, 13, 9, 71);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (206, 'Pilot Assembly Standard', 'NSF-approved component', 1761.81, 35, 5, 191);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (207, 'Fuse Mini', 'High-quality aftermarket part', 282.19, 52, 11, 250);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (208, 'Burner Assembly XL', 'Energy-efficient model', 381.88, 90, 12, 141);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (209, 'Expansion Valve 2HP', 'Universal fit component', 1602.18, 11, 5, 98);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (210, 'Bearing Assembly Mini', 'Universal fit component', 1215.19, 95, 3, 264);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (211, 'Control Board 3kW', 'NSF-approved component', 896.81, 18, 14, 463);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (212, 'Thermostat 24V', 'Precision-engineered replacement', 944.09, 44, 6, 379);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (213, 'Water Pump XL', 'NSF-approved component', 496.32, 50, 7, 140);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (214, 'Handle Assembly 24V', 'Heavy-duty industrial grade', 1767.53, 1, 2, 44);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (215, 'Control Board 200mm', 'Precision-engineered replacement', 996.2, 72, 7, 93);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (216, 'Ice Mold Standard', 'Heavy-duty industrial grade', 309.26, 47, 6, 423);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (217, 'Control Board 200mm', 'Precision-engineered replacement', 1529.1, 37, 5, 162);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (218, 'Water Pump 1HP', 'Precision-engineered replacement', 1906.81, 16, 12, 464);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (219, 'Compressor Motor 1HP', 'Universal fit component', 1016.96, 29, 13, 298);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (220, 'Ice Mold 200mm', 'Universal fit component', 296.86, 2, 6, 117);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (221, 'Grease Trap 3kW', 'Stainless steel construction', 364.46, 56, 8, 487);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (222, 'Wash Rack 200mm', 'Precision-engineered replacement', 1420.78, 83, 12, 25);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (223, 'Wash Rack 120mm', 'Heavy-duty industrial grade', 331.84, 13, 7, 165);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (224, 'Fuse 120mm', 'Precision-engineered replacement', 1681.99, 36, 11, 366);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (225, 'Drain Valve Standard', 'Universal fit component', 590.86, 31, 2, 7);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (226, 'Latch Assembly Mini', 'OEM replacement part', 1549.17, 58, 13, 35);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (227, 'Blade Assembly Mini', 'Food-safe certified', 618.28, 96, 12, 415);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (228, 'Blade Assembly 200mm', 'Stainless steel construction', 543.61, 31, 8, 487);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (229, 'Handle Assembly Pro', 'Universal fit component', 1425.18, 4, 5, 113);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (230, 'Timer 1HP', 'Commercial-grade component', 1240.55, 90, 6, 341);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (231, 'Vibration Pad 5kW', 'Energy-efficient model', 1803.61, 47, 6, 488);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (232, 'Hinge Pin 3kW', 'Food-safe certified', 61.53, 14, 12, 346);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (233, 'Power Cord 2HP', 'OEM replacement part', 311.6, 57, 6, 146);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (234, 'Heating Element Mini', 'Stainless steel construction', 583.92, 87, 2, 446);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (235, 'Relay Module 24V', 'Stainless steel construction', 1535.25, 45, 8, 170);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (236, 'Wash Rack 1HP', 'Universal fit component', 627.29, 3, 10, 310);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (237, 'O-Ring Set Pro', 'Energy-efficient model', 235.77, 76, 10, 352);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (238, 'Expansion Valve XL', 'Energy-efficient model', 1348.9, 60, 2, 463);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (239, 'Relay Module 24V', 'Food-safe certified', 1531.43, 74, 13, 415);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (240, 'Bearing Assembly XL', 'Stainless steel construction', 1912.56, 33, 4, 184);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (241, 'Bearing Assembly 1HP', 'Universal fit component', 682.03, 4, 7, 53);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (242, 'Contactor Mini', 'Food-safe certified', 1237.92, 81, 14, 372);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (243, 'Fuse 1HP', 'Universal fit component', 1654.74, 50, 13, 15);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (244, 'Capacitor 5kW', 'Heavy-duty industrial grade', 625.21, 82, 11, 280);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (245, 'Capacitor Pro', 'Energy-efficient model', 1404.24, 83, 2, 399);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (246, 'Float Switch 200mm', 'Stainless steel construction', 1429.08, 60, 12, 418);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (247, 'Bearing Assembly 200mm', 'Energy-efficient model', 432.65, 3, 3, 366);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (248, 'Thermostat Standard', 'Food-safe certified', 1072.46, 35, 7, 355);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (249, 'Expansion Valve 200mm', 'Stainless steel construction', 693.58, 44, 14, 110);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (250, 'Heating Element 1HP', 'Universal fit component', 70.87, 94, 9, 420);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (251, 'Circuit Breaker Mini', 'Food-safe certified', 1564.96, 48, 11, 194);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (252, 'Mounting Bracket 12V', 'Commercial-grade component', 1439.59, 90, 7, 176);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (253, 'Vibration Pad XL', 'Universal fit component', 194.97, 80, 12, 173);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (254, 'Water Inlet Valve 5kW', 'Heavy-duty industrial grade', 669.68, 16, 4, 5);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (255, 'Grease Trap 1HP', 'Food-safe certified', 847.62, 56, 9, 41);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (256, 'Pilot Assembly Pro', 'Universal fit component', 1013.37, 25, 13, 485);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (257, 'Seal Kit 24V', 'Food-safe certified', 516.08, 87, 3, 253);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (258, 'Spray Arm 3kW', 'Energy-efficient model', 1385.09, 66, 10, 285);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (259, 'Evaporator Coil 1HP', 'Food-safe certified', 231.43, 92, 14, 210);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (260, 'Seal Kit 12V', 'Stainless steel construction', 604.1, 16, 15, 445);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (261, 'Exhaust Duct Pro', 'Food-safe certified', 514.72, 86, 4, 20);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (262, 'Grate 1HP', 'NSF-approved component', 1554.61, 80, 15, 357);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (263, 'Compressor Motor 3kW', 'Food-safe certified', 1759.96, 50, 7, 291);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (264, 'Water Pump 24V', 'Precision-engineered replacement', 1997.68, 98, 6, 353);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (265, 'Defrost Heater 12V', 'Universal fit component', 1335.57, 3, 3, 258);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (266, 'Drip Tray Mini', 'Stainless steel construction', 1360.08, 63, 4, 159);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (267, 'Relay Module Standard', 'Commercial-grade component', 820.48, 12, 4, 335);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (268, 'Latch Assembly 24V', 'Universal fit component', 1095.44, 24, 12, 216);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (269, 'Relay Module 200mm', 'Food-safe certified', 1342.52, 71, 14, 427);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (270, 'Fuse 5kW', 'Heavy-duty industrial grade', 1775.52, 95, 13, 458);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (271, 'Mounting Bracket 2HP', 'Energy-efficient model', 404.51, 97, 12, 454);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (272, 'Mounting Bracket 200mm', 'Universal fit component', 1441.26, 59, 7, 298);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (273, 'Heating Element Pro', 'Food-safe certified', 612.76, 3, 9, 325);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (274, 'Clamp Mini', 'Precision-engineered replacement', 418.6, 30, 3, 30);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (275, 'Agitator 2HP', 'Stainless steel construction', 424.44, 47, 7, 308);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (276, 'Door Gasket Standard', 'Precision-engineered replacement', 1282.35, 1, 13, 334);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (277, 'Latch Assembly Mini', 'Food-safe certified', 1900.64, 99, 3, 379);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (278, 'Drain Valve XL', 'OEM replacement part', 656.01, 40, 2, 486);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (279, 'Power Cord 3kW', 'Energy-efficient model', 1233.78, 94, 6, 119);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (280, 'Exhaust Duct Mini', 'Universal fit component', 1222.33, 23, 13, 157);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (281, 'Power Cord 24V', 'Heavy-duty industrial grade', 226.33, 22, 2, 252);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (282, 'Pilot Assembly 2HP', 'Food-safe certified', 324.34, 56, 5, 367);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (283, 'Pressure Switch 120mm', 'NSF-approved component', 793.89, 95, 15, 195);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (284, 'Contactor 3kW', 'Precision-engineered replacement', 1027.79, 30, 15, 295);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (285, 'Clamp Mini', 'Food-safe certified', 1062.79, 80, 7, 437);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (286, 'Solenoid Valve 3kW', 'NSF-approved component', 247.95, 19, 15, 423);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (287, 'Belt Drive 2HP', 'Stainless steel construction', 329.91, 88, 14, 146);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (288, 'Expansion Valve 12V', 'Energy-efficient model', 1667.05, 84, 11, 296);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (289, 'Circuit Breaker 120mm', 'Commercial-grade component', 1407.75, 34, 5, 194);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (290, 'Thermostat 200mm', 'High-quality aftermarket part', 1322.93, 86, 15, 70);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (291, 'Water Pump 2HP', 'Universal fit component', 1039.54, 1, 9, 323);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (292, 'Ignition Module 3kW', 'OEM replacement part', 1056.56, 22, 5, 144);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (293, 'Spring Kit 1HP', 'OEM replacement part', 1461.68, 88, 4, 424);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (294, 'Condenser Coil Mini', 'Commercial-grade component', 1995.54, 79, 11, 11);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (295, 'Temperature Sensor 120mm', 'NSF-approved component', 1679.93, 96, 5, 317);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (296, 'Belt Drive 1HP', 'Commercial-grade component', 1693.76, 62, 15, 287);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (297, 'Wash Rack Mini', 'NSF-approved component', 296.82, 8, 7, 152);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (298, 'Expansion Valve Pro', 'Energy-efficient model', 126.82, 57, 10, 108);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (299, 'Hinge Pin 24V', 'OEM replacement part', 1807.76, 42, 10, 427);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (300, 'Wash Rack 120mm', 'Commercial-grade component', 1695.79, 64, 11, 169);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (301, 'Bearing Assembly 2HP', 'Universal fit component', 1791.22, 8, 8, 72);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (302, 'Timer 120mm', 'Heavy-duty industrial grade', 874.58, 73, 11, 13);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (303, 'Mounting Bracket XL', 'NSF-approved component', 1980.99, 60, 2, 71);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (304, 'Ignition Module Standard', 'High-quality aftermarket part', 1238.21, 65, 7, 33);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (305, 'Timer 120mm', 'Commercial-grade component', 1210.91, 54, 4, 178);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (306, 'Defrost Heater 2HP', 'Universal fit component', 872.08, 37, 5, 270);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (307, 'Evaporator Coil Mini', 'Stainless steel construction', 307.03, 50, 14, 389);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (308, 'Guard Cover Standard', 'Heavy-duty industrial grade', 87.64, 33, 7, 476);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (309, 'Control Board Mini', 'Commercial-grade component', 35.93, 21, 15, 88);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (310, 'Drip Tray 200mm', 'Energy-efficient model', 300.27, 3, 15, 229);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (311, 'Compressor Motor 5kW', 'Energy-efficient model', 1077.57, 2, 2, 30);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (312, 'Fan Motor 200mm', 'Heavy-duty industrial grade', 827.9, 58, 5, 437);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (313, 'Evaporator Coil XL', 'Universal fit component', 302.02, 57, 14, 222);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (314, 'Drip Tray 12V', 'High-quality aftermarket part', 193.09, 87, 12, 25);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (315, 'Agitator 2HP', 'Precision-engineered replacement', 1500.72, 49, 12, 137);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (316, 'Thermostat 5kW', 'Commercial-grade component', 706.44, 10, 5, 286);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (317, 'Heating Element 2HP', 'Precision-engineered replacement', 1620.17, 98, 8, 459);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (318, 'Defrost Heater 12V', 'OEM replacement part', 1110.25, 26, 14, 280);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (319, 'Thermostat 3kW', 'OEM replacement part', 1646.14, 74, 8, 279);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (320, 'Drip Tray XL', 'Food-safe certified', 1222.62, 32, 15, 446);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (321, 'Belt Drive Pro', 'Stainless steel construction', 694.35, 46, 13, 334);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (322, 'Burner Assembly 5kW', 'OEM replacement part', 768.6, 15, 10, 404);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (323, 'Float Switch 1HP', 'OEM replacement part', 625.14, 46, 7, 473);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (324, 'Heating Element 2HP', 'NSF-approved component', 844.02, 1, 15, 327);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (325, 'Condenser Coil 200mm', 'OEM replacement part', 688.21, 46, 4, 384);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (326, 'Fan Motor 1HP', 'Stainless steel construction', 332.93, 56, 11, 301);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (327, 'Circuit Breaker Mini', 'Energy-efficient model', 399.47, 38, 5, 418);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (328, 'Control Board 2HP', 'Stainless steel construction', 24.44, 12, 5, 41);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (329, 'Seal Kit 200mm', 'Commercial-grade component', 821.21, 23, 15, 394);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (330, 'Contactor XL', 'Commercial-grade component', 1863.47, 22, 11, 468);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (331, 'Timer XL', 'Energy-efficient model', 1919.0, 74, 5, 329);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (332, 'Grate XL', 'OEM replacement part', 1981.18, 83, 7, 374);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (333, 'Burner Assembly 200mm', 'Energy-efficient model', 1785.45, 93, 6, 157);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (334, 'Handle Assembly 3kW', 'High-quality aftermarket part', 664.59, 21, 14, 213);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (335, 'Power Cord XL', 'Universal fit component', 159.39, 6, 5, 360);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (336, 'Door Gasket XL', 'NSF-approved component', 178.3, 28, 13, 11);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (337, 'Drip Tray 5kW', 'Universal fit component', 1257.99, 95, 13, 422);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (338, 'Water Pump 120mm', 'Commercial-grade component', 662.38, 98, 8, 291);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (339, 'Expansion Valve 12V', 'OEM replacement part', 1332.16, 23, 5, 51);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (340, 'Pilot Assembly Standard', 'Heavy-duty industrial grade', 272.98, 68, 2, 395);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (341, 'Belt Drive Standard', 'Precision-engineered replacement', 1007.01, 62, 4, 2);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (342, 'Gas Valve 1HP', 'Energy-efficient model', 1788.9, 45, 11, 72);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (343, 'Capacitor Pro', 'Precision-engineered replacement', 1259.02, 60, 9, 179);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (344, 'Ice Mold 1HP', 'Energy-efficient model', 942.62, 40, 14, 261);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (345, 'Float Switch Standard', 'Heavy-duty industrial grade', 1071.07, 1, 14, 420);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (346, 'Drain Valve Standard', 'Heavy-duty industrial grade', 1107.24, 44, 5, 461);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (347, 'Filter Cartridge 200mm', 'NSF-approved component', 1267.19, 42, 13, 441);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (348, 'Grate 12V', 'Food-safe certified', 1398.77, 55, 6, 19);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (349, 'Burner Assembly XL', 'NSF-approved component', 1154.44, 40, 7, 177);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (350, 'Wash Rack XL', 'OEM replacement part', 1299.03, 98, 5, 468);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (351, 'Pilot Assembly 120mm', 'Heavy-duty industrial grade', 272.72, 32, 11, 107);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (352, 'Ignition Module Mini', 'Universal fit component', 1070.69, 67, 11, 28);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (353, 'Condenser Coil 3kW', 'Precision-engineered replacement', 1927.13, 90, 8, 393);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (354, 'Contactor 5kW', 'Precision-engineered replacement', 896.22, 93, 8, 384);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (355, 'Guard Cover 200mm', 'High-quality aftermarket part', 227.3, 64, 2, 20);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (356, 'Circuit Breaker 3kW', 'High-quality aftermarket part', 1366.94, 6, 3, 362);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (357, 'Power Cord 5kW', 'Commercial-grade component', 1133.21, 23, 14, 138);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (358, 'Clamp Pro', 'Heavy-duty industrial grade', 1402.33, 31, 2, 75);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (359, 'Grease Trap 1HP', 'High-quality aftermarket part', 559.19, 13, 4, 143);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (360, 'Evaporator Coil XL', 'Stainless steel construction', 477.68, 25, 6, 384);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (361, 'Belt Drive Mini', 'Precision-engineered replacement', 499.74, 55, 8, 197);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (362, 'Handle Assembly XL', 'OEM replacement part', 201.85, 5, 5, 426);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (363, 'Capacitor 120mm', 'OEM replacement part', 967.65, 36, 7, 141);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (364, 'Capacitor Mini', 'High-quality aftermarket part', 1433.9, 37, 7, 267);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (365, 'Hinge Pin 120mm', 'Energy-efficient model', 1174.11, 52, 6, 419);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (366, 'Defrost Heater 3kW', 'Stainless steel construction', 756.09, 3, 12, 307);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (367, 'Temperature Sensor 5kW', 'Heavy-duty industrial grade', 856.68, 62, 9, 127);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (368, 'Power Cord Mini', 'Food-safe certified', 368.48, 18, 12, 242);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (369, 'Solenoid Valve 2HP', 'Commercial-grade component', 1405.27, 16, 6, 12);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (370, 'Grease Trap Mini', 'Food-safe certified', 590.9, 18, 5, 46);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (371, 'Blade Assembly Standard', 'Commercial-grade component', 1974.5, 23, 10, 295);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (372, 'Timer 24V', 'Commercial-grade component', 1607.2, 98, 12, 323);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (373, 'Fan Motor Mini', 'Precision-engineered replacement', 40.35, 32, 7, 265);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (374, 'Condenser Coil 5kW', 'NSF-approved component', 1038.76, 56, 3, 242);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (375, 'Expansion Valve Mini', 'NSF-approved component', 248.91, 66, 10, 192);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (376, 'Control Board XL', 'Stainless steel construction', 1832.84, 100, 8, 198);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (377, 'Gas Valve XL', 'Stainless steel construction', 1958.16, 72, 15, 247);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (378, 'Evaporator Coil 200mm', 'Heavy-duty industrial grade', 1741.69, 83, 7, 143);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (379, 'Mounting Bracket 200mm', 'Food-safe certified', 356.51, 5, 10, 406);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (380, 'Grate 1HP', 'Heavy-duty industrial grade', 713.12, 99, 14, 67);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (381, 'Temperature Sensor 12V', 'High-quality aftermarket part', 452.34, 7, 3, 377);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (382, 'Vibration Pad 12V', 'Commercial-grade component', 740.98, 40, 5, 75);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (383, 'Circuit Breaker Pro', 'Food-safe certified', 1259.0, 67, 5, 211);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (384, 'Control Board Pro', 'Energy-efficient model', 1907.84, 86, 14, 154);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (385, 'Heating Element 24V', 'High-quality aftermarket part', 1151.62, 54, 15, 347);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (386, 'Capacitor 200mm', 'Commercial-grade component', 784.19, 79, 10, 77);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (387, 'Exhaust Duct 24V', 'Stainless steel construction', 1657.3, 94, 11, 79);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (388, 'O-Ring Set 5kW', 'High-quality aftermarket part', 1878.51, 32, 12, 67);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (389, 'Power Cord 2HP', 'Universal fit component', 1050.56, 27, 7, 277);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (390, 'Bearing Assembly Standard', 'NSF-approved component', 426.07, 86, 4, 17);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (391, 'Mounting Bracket 3kW', 'Energy-efficient model', 60.65, 83, 8, 347);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (392, 'Capacitor 5kW', 'Food-safe certified', 1806.13, 66, 9, 273);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (393, 'Defrost Heater 12V', 'Commercial-grade component', 1578.87, 21, 9, 437);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (394, 'Burner Assembly 120mm', 'Heavy-duty industrial grade', 18.23, 40, 5, 444);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (395, 'Pressure Switch 3kW', 'High-quality aftermarket part', 884.45, 78, 5, 458);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (396, 'Wash Rack 3kW', 'High-quality aftermarket part', 718.54, 15, 7, 73);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (397, 'Seal Kit XL', 'OEM replacement part', 1727.67, 77, 2, 80);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (398, 'Mounting Bracket 12V', 'Precision-engineered replacement', 578.21, 17, 5, 124);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (399, 'Grease Trap Mini', 'NSF-approved component', 1645.18, 50, 9, 386);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (400, 'Grate 5kW', 'Heavy-duty industrial grade', 1157.23, 70, 6, 477);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (401, 'Mounting Bracket Mini', 'High-quality aftermarket part', 964.81, 36, 2, 246);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (402, 'Latch Assembly 120mm', 'NSF-approved component', 587.26, 42, 12, 464);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (403, 'Spray Arm 120mm', 'Stainless steel construction', 1242.67, 61, 10, 162);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (404, 'Bearing Assembly Mini', 'Precision-engineered replacement', 1845.33, 69, 6, 40);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (405, 'Compressor Motor 24V', 'High-quality aftermarket part', 362.07, 54, 3, 227);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (406, 'Mounting Bracket 200mm', 'High-quality aftermarket part', 539.22, 78, 2, 80);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (407, 'Control Board 200mm', 'Energy-efficient model', 1409.29, 17, 5, 234);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (408, 'Drip Tray 24V', 'Universal fit component', 1937.16, 64, 5, 10);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (409, 'Grate 2HP', 'Stainless steel construction', 94.54, 17, 13, 199);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (410, 'Clamp 24V', 'Universal fit component', 458.47, 29, 4, 409);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (411, 'Defrost Heater Mini', 'Commercial-grade component', 1740.01, 21, 6, 360);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (412, 'Contactor 200mm', 'Heavy-duty industrial grade', 524.03, 47, 9, 324);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (413, 'Grease Trap 1HP', 'OEM replacement part', 789.2, 69, 5, 195);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (414, 'Handle Assembly Mini', 'Energy-efficient model', 1324.1, 69, 15, 121);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (415, 'Latch Assembly 24V', 'OEM replacement part', 1449.79, 80, 5, 120);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (416, 'Blade Assembly Mini', 'Energy-efficient model', 83.56, 45, 15, 296);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (417, 'Wash Rack 1HP', 'Stainless steel construction', 1972.65, 4, 12, 426);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (418, 'Fuse Mini', 'High-quality aftermarket part', 369.37, 28, 11, 213);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (419, 'Ice Mold 12V', 'NSF-approved component', 1632.5, 38, 13, 313);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (420, 'Evaporator Coil 2HP', 'Precision-engineered replacement', 1330.86, 53, 2, 422);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (421, 'Thermostat 12V', 'Universal fit component', 296.78, 65, 15, 370);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (422, 'Circuit Breaker Mini', 'High-quality aftermarket part', 1210.69, 85, 12, 79);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (423, 'Clamp Standard', 'High-quality aftermarket part', 1022.71, 99, 4, 173);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (424, 'Vibration Pad 1HP', 'Heavy-duty industrial grade', 1497.29, 32, 8, 25);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (425, 'Seal Kit 120mm', 'OEM replacement part', 445.44, 43, 2, 435);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (426, 'Grate 5kW', 'Energy-efficient model', 95.48, 18, 15, 405);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (427, 'Water Inlet Valve 2HP', 'Universal fit component', 786.0, 32, 6, 235);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (428, 'Control Board 12V', 'NSF-approved component', 1081.75, 42, 13, 437);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (429, 'Wash Rack Pro', 'Precision-engineered replacement', 244.48, 66, 2, 340);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (430, 'Defrost Heater 24V', 'Heavy-duty industrial grade', 1170.36, 56, 6, 452);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (431, 'Compressor Motor 2HP', 'Universal fit component', 1184.62, 13, 15, 120);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (432, 'Filter Cartridge 2HP', 'OEM replacement part', 166.43, 0, 11, 399);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (433, 'Burner Assembly 5kW', 'OEM replacement part', 427.23, 46, 5, 126);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (434, 'Drip Tray Mini', 'Stainless steel construction', 368.73, 97, 3, 351);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (435, 'Door Gasket Standard', 'Food-safe certified', 999.04, 15, 7, 435);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (436, 'Handle Assembly 24V', 'Stainless steel construction', 1433.55, 81, 11, 422);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (437, 'Filter Cartridge 12V', 'Stainless steel construction', 408.98, 6, 9, 462);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (438, 'Compressor Motor 3kW', 'OEM replacement part', 835.24, 96, 14, 440);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (439, 'Guard Cover 5kW', 'Energy-efficient model', 1265.77, 34, 3, 35);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (440, 'Circuit Breaker 120mm', 'Food-safe certified', 1551.71, 9, 14, 180);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (441, 'Condenser Coil 200mm', 'Heavy-duty industrial grade', 1038.49, 91, 2, 42);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (442, 'Fan Motor 1HP', 'Food-safe certified', 1496.85, 30, 9, 197);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (443, 'Power Cord 24V', 'Stainless steel construction', 451.59, 12, 4, 138);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (444, 'Spring Kit 24V', 'Universal fit component', 1521.07, 10, 13, 338);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (445, 'Agitator 200mm', 'Precision-engineered replacement', 223.08, 41, 12, 232);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (446, 'Pilot Assembly Pro', 'Precision-engineered replacement', 1320.97, 40, 6, 257);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (447, 'Condenser Coil Standard', 'Food-safe certified', 1888.28, 30, 7, 51);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (448, 'Drip Tray 3kW', 'Commercial-grade component', 588.52, 98, 4, 415);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (449, 'Spray Arm 24V', 'Precision-engineered replacement', 1301.58, 33, 8, 285);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (450, 'Wash Rack 3kW', 'Energy-efficient model', 1450.53, 26, 9, 101);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (451, 'Vibration Pad 12V', 'NSF-approved component', 1284.48, 65, 11, 391);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (452, 'Vibration Pad Pro', 'Heavy-duty industrial grade', 712.9, 66, 12, 199);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (453, 'Exhaust Duct 200mm', 'Universal fit component', 370.8, 32, 8, 161);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (454, 'Solenoid Valve 5kW', 'Stainless steel construction', 519.52, 48, 9, 97);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (455, 'Grate 24V', 'NSF-approved component', 1606.16, 75, 4, 191);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (456, 'Water Inlet Valve Mini', 'Commercial-grade component', 1191.29, 31, 7, 399);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (457, 'Relay Module XL', 'Heavy-duty industrial grade', 1730.01, 32, 9, 85);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (458, 'Fuse Standard', 'Precision-engineered replacement', 195.55, 67, 15, 16);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (459, 'Power Cord Standard', 'Precision-engineered replacement', 15.52, 25, 14, 236);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (460, 'Evaporator Coil 1HP', 'Heavy-duty industrial grade', 786.97, 24, 8, 1);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (461, 'Condenser Coil 2HP', 'Precision-engineered replacement', 1695.24, 56, 5, 157);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (462, 'Hinge Pin Pro', 'High-quality aftermarket part', 1720.99, 41, 5, 316);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (463, 'Mounting Bracket Mini', 'NSF-approved component', 118.53, 50, 13, 137);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (464, 'Fan Motor 200mm', 'OEM replacement part', 182.62, 29, 5, 80);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (465, 'Ice Mold 120mm', 'Stainless steel construction', 1241.32, 45, 11, 334);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (466, 'Solenoid Valve XL', 'Heavy-duty industrial grade', 1428.15, 21, 10, 220);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (467, 'Thermostat 200mm', 'NSF-approved component', 1440.41, 94, 8, 82);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (468, 'Thermostat Pro', 'NSF-approved component', 1053.46, 64, 7, 81);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (469, 'Drip Tray 200mm', 'Commercial-grade component', 1506.15, 32, 2, 78);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (470, 'Clamp Mini', 'Energy-efficient model', 13.37, 61, 5, 351);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (471, 'Pressure Switch Mini', 'High-quality aftermarket part', 348.99, 64, 7, 295);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (472, 'Mounting Bracket Standard', 'Heavy-duty industrial grade', 731.41, 21, 13, 179);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (473, 'Drip Tray 1HP', 'Commercial-grade component', 1306.48, 38, 13, 82);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (474, 'Drip Tray Standard', 'Universal fit component', 752.57, 43, 6, 369);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (475, 'Fan Motor 24V', 'Food-safe certified', 1485.95, 49, 6, 401);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (476, 'Power Cord 12V', 'Heavy-duty industrial grade', 1375.63, 3, 12, 212);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (477, 'Blade Assembly 24V', 'OEM replacement part', 1145.34, 77, 12, 73);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (478, 'Evaporator Coil Mini', 'Universal fit component', 825.56, 47, 14, 153);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (479, 'Spring Kit 200mm', 'High-quality aftermarket part', 1130.03, 31, 3, 375);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (480, 'Agitator Standard', 'Food-safe certified', 1926.27, 82, 2, 207);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (481, 'Grease Trap 1HP', 'Food-safe certified', 317.95, 16, 11, 402);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (482, 'Solenoid Valve 24V', 'Food-safe certified', 1475.94, 72, 5, 381);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (483, 'Compressor Motor Standard', 'Energy-efficient model', 1284.33, 98, 15, 140);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (484, 'Bearing Assembly 2HP', 'Heavy-duty industrial grade', 335.11, 51, 10, 311);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (485, 'Drain Valve 120mm', 'Universal fit component', 1807.56, 15, 3, 146);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (486, 'Water Inlet Valve 200mm', 'NSF-approved component', 1397.04, 49, 10, 422);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (487, 'Gas Valve 2HP', 'NSF-approved component', 1517.27, 61, 2, 330);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (488, 'Seal Kit 2HP', 'Stainless steel construction', 1903.86, 85, 15, 42);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (489, 'Burner Assembly Standard', 'Heavy-duty industrial grade', 321.3, 35, 4, 201);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (490, 'Drain Valve 1HP', 'OEM replacement part', 699.51, 82, 3, 2);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (491, 'Drip Tray 120mm', 'Heavy-duty industrial grade', 30.61, 55, 9, 50);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (492, 'Blade Assembly Mini', 'Heavy-duty industrial grade', 159.93, 69, 9, 293);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (493, 'Capacitor 3kW', 'Food-safe certified', 1400.25, 24, 10, 24);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (494, 'Evaporator Coil 120mm', 'Commercial-grade component', 650.63, 74, 4, 119);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (495, 'Temperature Sensor 200mm', 'NSF-approved component', 526.14, 72, 3, 34);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (496, 'Evaporator Coil 24V', 'NSF-approved component', 1160.03, 31, 9, 206);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (497, 'Float Switch 24V', 'NSF-approved component', 1158.08, 25, 2, 121);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (498, 'Heating Element 200mm', 'Precision-engineered replacement', 1723.47, 21, 12, 32);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (499, 'Circuit Breaker Standard', 'Universal fit component', 1053.49, 24, 5, 340);
insert into SparePart (part_id, name, description, unit_price, stock_quantity, minimum_stock, supplier_id) values (500, 'Condenser Coil Standard', 'Food-safe certified', 1094.66, 2, 7, 171);
