insert into Technician (technician_id, name, phone, specialization) values (1, 'Ruth Fischer', '059-9183497', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (2, 'Paz Katz', '052-9783730', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (3, 'Uri Hadad', '055-9403285', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (4, 'Shira Mizrahi', '050-6336592', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (5, 'Roi Goldstein', '051-9396582', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (6, 'Hila Biton', '051-7363749', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (7, 'Sivan Malka', '053-5185760', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (8, 'Yael Natan', '054-8090012', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (9, 'Shai Tzur', '053-2956688', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (10, 'Gil Goldstein', '059-6676591', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (11, 'Gal Jacobi', '058-8346236', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (12, 'Tal Gabay', '051-4567887', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (13, 'Yoav Shalom', '057-6363104', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (14, 'Eden Shalom', '056-5091075', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (15, 'Yuval Hadad', '053-5839943', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (16, 'Shai Golan', '056-7475322', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (17, 'Alon Natan', '057-4027219', 'HVAC and Ventilation');
insert into Technician (technician_id, name, phone, specialization) values (18, 'Ofir Shapira', '056-7858969', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (19, 'Uri Biton', '055-4269606', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (20, 'Noa Peretz', '055-4583312', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (21, 'Lia Alon', '050-4402998', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (22, 'Tomer Russo', '051-6071082', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (23, 'Ofir Katz', '059-2565803', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (24, 'Dina Shalom', '052-5527948', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (25, 'Yael Regev', '053-4645950', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (26, 'Ran Gabay', '059-5337600', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (27, 'Tomer Alon', '057-7822942', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (28, 'Ruth Levy', '050-5505755', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (29, 'Tal Chai', '056-6437424', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (30, 'Chen Bar', '054-2205541', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (31, 'Noam Peretz', '059-7095861', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (32, 'Ben Mizrahi', '054-7934228', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (33, 'Roni Levi', '055-2409347', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (34, 'Eyal Biton', '057-5312424', 'HVAC and Ventilation');
insert into Technician (technician_id, name, phone, specialization) values (35, 'Ariel Gabay', '054-1801083', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (36, 'Adam Israeli', '056-5593920', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (37, 'Nir Natan', '050-6547345', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (38, 'Ran Natan', '056-6451710', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (39, 'Ido Levi', '053-8276233', 'HVAC and Ventilation');
insert into Technician (technician_id, name, phone, specialization) values (40, 'Lia Klein', '056-2798135', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (41, 'Ran Vaknin', '050-2750605', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (42, 'Roi Cohen', '057-6994108', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (43, 'Tamar Zilberman', '051-1630925', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (44, 'Yael Jacobi', '055-9303928', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (45, 'Itai Regev', '053-1237747', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (46, 'Shai Ohayon', '057-3096078', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (47, 'Paz Ohayon', '056-1742905', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (48, 'Nir Levi', '050-4898586', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (49, 'Dan Tzur', '054-6525789', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (50, 'Nir Mizrahi', '056-2635105', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (51, 'Chen Gabay', '053-3507461', 'HVAC and Ventilation');
insert into Technician (technician_id, name, phone, specialization) values (52, 'Keren Malka', '051-9189284', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (53, 'Roni Tzur', '051-7771149', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (54, 'Sivan Biton', '054-8893481', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (55, 'Elad Bar', '055-5480575', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (56, 'Ran Levi', '054-2857474', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (57, 'Ziv Friedman', '059-9857946', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (58, 'Lior Nahum', '059-4952483', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (59, 'Yuval Alon', '053-8182920', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (60, 'Roni Klein', '058-3321591', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (61, 'Elad Vaknin', '054-9100329', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (62, 'Ran Friedman', '056-7040837', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (63, 'Keren Dahan', '051-4088561', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (64, 'Paz Nahum', '057-3183621', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (65, 'Gil Oz', '052-1217112', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (66, 'Michal Hadad', '059-7777080', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (67, 'Liora Tzur', '056-5953601', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (68, 'Ariel Avraham', '056-1105190', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (69, 'Uri Gabay', '053-9620019', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (70, 'Itai Shapira', '056-3040956', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (71, 'Itai Bar', '058-8639199', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (72, 'Amit Ben-David', '053-1979536', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (73, 'Ofir Bar', '058-1977802', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (74, 'Gal Alon', '056-4705556', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (75, 'Chen Vaknin', '056-4592727', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (76, 'Chen Regev', '050-8762065', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (77, 'Alon Goldstein', '058-6773960', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (78, 'Elad Friedman', '051-5285032', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (79, 'Lia Gabay', '051-1486596', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (80, 'Roi Zilberman', '050-2387727', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (81, 'Avi Golan', '053-4647213', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (82, 'Uri Vaknin', '054-6429218', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (83, 'Itai Gabay', '058-3357352', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (84, 'Tomer Peled', '052-3980390', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (85, 'Chen Peretz', '058-5830729', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (86, 'Lior Regev', '050-3112963', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (87, 'Paz Jacobi', '056-2852346', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (88, 'Noam Mizrahi', '055-3484477', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (89, 'Ben Nahum', '057-6437865', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (90, 'Dan Biton', '055-6999879', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (91, 'Miri Israeli', '059-7648690', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (92, 'Eyal Israeli', '050-2844258', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (93, 'Dor Nahum', '057-2679037', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (94, 'Eden Avraham', '051-6927504', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (95, 'Nir Levi', '053-1563609', 'HVAC and Ventilation');
insert into Technician (technician_id, name, phone, specialization) values (96, 'Shira Jacobi', '052-3520427', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (97, 'Shira Cohen', '051-6823974', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (98, 'Chen Peretz', '058-5746476', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (99, 'Dor Azulay', '055-8726069', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (100, 'Uri Haim', '057-8451358', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (101, 'Ofir Cohen', '051-2912514', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (102, 'Yuval Alon', '053-7913806', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (103, 'Ruth Jacobi', '051-3282492', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (104, 'Eden Golan', '057-4455664', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (105, 'Dina Golan', '052-1287305', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (106, 'Dan Malka', '052-6638994', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (107, 'Naomi Natan', '051-3104030', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (108, 'Ran Levi', '057-8056685', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (109, 'Nir Katz', '050-8129890', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (110, 'Roi Levy', '056-3301562', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (111, 'Eyal Ohayon', '057-5192425', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (112, 'Oren Levi', '057-7569663', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (113, 'Amit Israeli', '056-5497459', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (114, 'Gal Peretz', '057-1497317', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (115, 'Lia Ben-David', '058-9336536', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (116, 'Oren Mizrahi', '054-9286961', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (117, 'Dina Biton', '051-3153060', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (118, 'Ofir Fischer', '056-5377179', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (119, 'Hila Katz', '050-1369360', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (120, 'Yuval Mizrahi', '059-6275519', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (121, 'Ido Nahum', '051-5171983', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (122, 'Michal Fischer', '053-8071379', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (123, 'Adam Peretz', '056-8162518', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (124, 'Itai Golan', '055-9708767', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (125, 'Paz Shalom', '059-1041289', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (126, 'Shai Levy', '052-5629261', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (127, 'Naomi Mizrahi', '053-2440121', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (128, 'Ariel Natan', '057-6525314', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (129, 'Tamar Goldstein', '050-4570282', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (130, 'Roni Avraham', '057-2613222', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (131, 'Shira Goldstein', '051-4911840', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (132, 'Amit Shapira', '050-9132609', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (133, 'Amit Levi', '057-6202232', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (134, 'Yuval Haim', '053-6676794', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (135, 'Roi Levy', '058-4382902', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (136, 'Lior Avraham', '053-6584973', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (137, 'Ariel Biton', '056-1871507', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (138, 'Yuval Yosef', '050-2990983', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (139, 'Ziv Hadad', '054-4674489', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (140, 'Ziv Fischer', '051-7203667', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (141, 'Tal Chai', '050-6159611', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (142, 'Adam Israeli', '051-1926252', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (143, 'Oren Bar', '059-2114702', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (144, 'Avi Oz', '054-8711431', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (145, 'Yuval Fischer', '057-5706787', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (146, 'Shira Gabay', '056-2653616', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (147, 'Itai Jacobi', '054-3652399', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (148, 'Amit Gabay', '050-6963296', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (149, 'Ariel Ben-David', '053-8561451', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (150, 'Shira Yosef', '052-4630348', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (151, 'Dina Israeli', '051-6563032', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (152, 'Naomi Chai', '050-3069759', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (153, 'Elad Malka', '053-8840583', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (154, 'Ariel Azulay', '052-8179594', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (155, 'Alon Levy', '052-3107788', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (156, 'Naomi Elimelech', '056-7946962', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (157, 'Alon Nahum', '051-3101144', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (158, 'Alon Alon', '053-1993201', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (159, 'Hila Chai', '058-2173171', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (160, 'Roi Alon', '052-5242286', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (161, 'Roni Zilberman', '057-3405306', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (162, 'Chen Peretz', '056-2077913', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (163, 'Maya Mor', '052-4179137', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (164, 'Maya Peretz', '052-5173924', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (165, 'Chen Dahan', '055-9330818', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (166, 'Uri Azulay', '053-5881615', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (167, 'Miri Shalom', '052-3014493', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (168, 'Hila Russo', '059-6147700', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (169, 'Dan Vaknin', '055-9059426', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (170, 'Gal Golan', '059-3688521', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (171, 'Liora Shapira', '058-2138528', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (172, 'Gal Hadad', '050-9946781', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (173, 'Hila Chai', '055-6643695', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (174, 'Liora Ben-David', '058-3420346', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (175, 'Ariel Mor', '051-7458971', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (176, 'Maya Dahan', '056-3904681', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (177, 'Elad Bar', '054-5867051', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (178, 'Tomer Alon', '059-9227148', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (179, 'Hila Peled', '059-6504811', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (180, 'Ran Israeli', '052-7791129', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (181, 'Itai Biton', '051-7767772', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (182, 'Uri Haim', '054-1241745', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (183, 'Lior Jacobi', '056-7420361', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (184, 'Yoav Katz', '051-7684666', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (185, 'Eden Klein', '051-6765740', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (186, 'Ido Friedman', '053-1451581', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (187, 'Oren Jacobi', '053-6968834', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (188, 'Ben Russo', '056-9868010', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (189, 'Paz Regev', '054-7121979', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (190, 'Alon Gabay', '050-1435197', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (191, 'Yael Chai', '054-4134664', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (192, 'Lior Ben-David', '050-9484130', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (193, 'Tamar Goldstein', '058-8827889', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (194, 'Nir Malka', '055-2629337', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (195, 'Gil Tzur', '054-2566827', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (196, 'Ben Azulay', '057-3518357', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (197, 'Sivan Azulay', '056-9980638', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (198, 'Ran Peretz', '053-9358500', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (199, 'Maya Jacobi', '058-8637070', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (200, 'Eden Goldstein', '052-9782617', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (201, 'Dan Oz', '056-9066206', 'HVAC and Ventilation');
insert into Technician (technician_id, name, phone, specialization) values (202, 'Gil Mor', '055-8454752', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (203, 'Ariel Cohen', '056-6124953', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (204, 'Itai Vaknin', '051-1355424', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (205, 'Ariel Klein', '059-8059312', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (206, 'Ruth Ben-David', '057-7659393', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (207, 'Hila Jacobi', '059-4575382', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (208, 'Eden Levi', '051-1955330', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (209, 'Shira Bar', '050-4332660', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (210, 'Roni Regev', '057-9224471', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (211, 'Chen Friedman', '056-3304506', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (212, 'Ariel Chai', '051-2653415', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (213, 'Uri Klein', '056-9785172', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (214, 'Alon Shalom', '051-4269172', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (215, 'Dor Mizrahi', '053-4585795', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (216, 'Gal Peretz', '056-6265675', 'HVAC and Ventilation');
insert into Technician (technician_id, name, phone, specialization) values (217, 'Michal Israeli', '055-6054986', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (218, 'Elad Nahum', '055-4574861', 'HVAC and Ventilation');
insert into Technician (technician_id, name, phone, specialization) values (219, 'Noa Katz', '052-9444706', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (220, 'Noam Nahum', '059-2592823', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (221, 'Roni Peled', '053-8814776', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (222, 'Tal Levi', '053-1272844', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (223, 'Avi Shapira', '059-1602006', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (224, 'Shai Azulay', '050-7741750', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (225, 'Ofir Yosef', '055-1846720', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (226, 'Naomi Zilberman', '054-5418871', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (227, 'Shai Biton', '051-3770655', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (228, 'Ruth Azulay', '058-2245533', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (229, 'Nir Yosef', '050-8584909', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (230, 'Avi Vaknin', '058-8351529', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (231, 'Noam Avraham', '057-3901851', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (232, 'Yossi Dahan', '051-3334577', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (233, 'Tom Azulay', '054-5650549', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (234, 'Ido Goldstein', '056-6654357', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (235, 'Yossi Regev', '053-5929634', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (236, 'Paz Fischer', '055-8466633', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (237, 'Paz Jacobi', '054-8183367', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (238, 'Gal Bar', '050-9756268', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (239, 'Ariel Shalom', '055-1829920', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (240, 'Gal Azulay', '053-2081988', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (241, 'Yossi Goldstein', '052-2111608', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (242, 'Tom Avraham', '059-9205845', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (243, 'Dan Hadad', '053-1076881', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (244, 'Lior Alon', '050-1142390', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (245, 'Naomi Peretz', '057-9366106', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (246, 'Lia Bar', '057-7274343', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (247, 'Naomi Katz', '053-4540783', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (248, 'Ran Chai', '057-3147802', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (249, 'Oren Nahum', '054-9681957', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (250, 'Omer Biton', '052-4022308', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (251, 'Liora Chai', '058-8006442', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (252, 'Lior Bar', '054-5426542', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (253, 'Avi Biton', '053-5876372', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (254, 'Tomer Klein', '059-2276899', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (255, 'Uri Mizrahi', '055-9723220', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (256, 'Gil Shapira', '055-9628891', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (257, 'Ido Yosef', '056-7729729', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (258, 'Hila Natan', '058-1394090', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (259, 'Dan Biton', '056-8546683', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (260, 'Ziv Yosef', '054-8216200', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (261, 'Roi Nahum', '052-5277528', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (262, 'Chen Vaknin', '056-8082492', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (263, 'Alon Yosef', '054-5862283', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (264, 'Itai Ben-David', '051-8822762', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (265, 'Ruth Malka', '056-5226504', 'HVAC and Ventilation');
insert into Technician (technician_id, name, phone, specialization) values (266, 'Yael Alon', '056-6115580', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (267, 'Naomi Zilberman', '051-1695379', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (268, 'Maya Mor', '052-5636866', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (269, 'Eden Shapira', '050-8889179', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (270, 'Shai Azulay', '057-9847576', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (271, 'Nir Dahan', '052-4912106', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (272, 'Shai Elimelech', '050-5062192', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (273, 'Noa Oz', '050-3197636', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (274, 'Roni Natan', '051-1367467', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (275, 'Oren Cohen', '050-3192515', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (276, 'Eyal Haim', '051-6676303', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (277, 'Dina Natan', '051-3606438', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (278, 'Michal Peretz', '055-4585196', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (279, 'Yael Azulay', '053-4760522', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (280, 'Omer Mizrahi', '059-2717745', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (281, 'Ido Bar', '057-3912294', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (282, 'Liora Zilberman', '055-4212340', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (283, 'Tamar Goldstein', '050-1923505', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (284, 'Gil Elimelech', '055-8369482', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (285, 'Tamar Gabay', '056-1910263', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (286, 'Maya Haim', '054-7224023', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (287, 'Elad Yosef', '058-5191827', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (288, 'Lior Peled', '050-6700879', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (289, 'Yoav Ben-David', '058-8098435', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (290, 'Oren Avraham', '059-1693764', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (291, 'Maya Regev', '053-9129516', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (292, 'Lia Russo', '054-8040007', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (293, 'Shira Haim', '054-8874302', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (294, 'Yuval Peled', '053-5900981', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (295, 'Itai Regev', '052-8623829', 'HVAC and Ventilation');
insert into Technician (technician_id, name, phone, specialization) values (296, 'Ran Russo', '052-4920356', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (297, 'Miri Elimelech', '053-7967913', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (298, 'Alon Vaknin', '051-2690435', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (299, 'Tal Cohen', '050-5039456', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (300, 'Tal Hadad', '059-2101683', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (301, 'Alon Israeli', '052-2669467', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (302, 'Tom Dahan', '056-9973460', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (303, 'Yuval Tzur', '056-4489109', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (304, 'Gal Oz', '058-6501951', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (305, 'Noam Alon', '054-3933023', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (306, 'Tomer Regev', '052-7163789', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (307, 'Ido Friedman', '055-6831461', 'HVAC and Ventilation');
insert into Technician (technician_id, name, phone, specialization) values (308, 'Roni Bar', '057-5974298', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (309, 'Keren Biton', '055-9632990', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (310, 'Ofir Ohayon', '057-8033550', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (311, 'Dor Mizrahi', '053-8142418', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (312, 'Eyal Biton', '050-2450159', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (313, 'Shira Avraham', '055-9445697', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (314, 'Ziv Avraham', '056-6647809', 'HVAC and Ventilation');
insert into Technician (technician_id, name, phone, specialization) values (315, 'Sivan Biton', '057-1949991', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (316, 'Tal Shapira', '050-8038576', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (317, 'Nir Israeli', '059-9116342', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (318, 'Adam Regev', '056-2088732', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (319, 'Elad Gabay', '053-5837708', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (320, 'Gil Zilberman', '054-6154578', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (321, 'Eden Levy', '059-8829205', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (322, 'Michal Mizrahi', '058-6443931', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (323, 'Ziv Dahan', '050-8814590', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (324, 'Dor Oz', '051-4848473', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (325, 'Noam Levi', '050-1720530', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (326, 'Liora Chai', '057-4659910', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (327, 'Tal Mor', '057-3600196', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (328, 'Nir Elimelech', '059-2503529', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (329, 'Sivan Shapira', '058-9990108', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (330, 'Roni Bar', '054-8168726', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (331, 'Roni Dahan', '051-6530884', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (332, 'Liora Alon', '052-2636885', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (333, 'Hila Gabay', '055-8743175', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (334, 'Ran Avraham', '054-9256545', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (335, 'Ariel Ben-David', '056-6937745', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (336, 'Naomi Cohen', '059-9579279', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (337, 'Roi Natan', '058-9297254', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (338, 'Ben Peled', '057-8573425', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (339, 'Alon Natan', '054-1777414', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (340, 'Hila Fischer', '057-3510816', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (341, 'Sivan Klein', '051-1306582', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (342, 'Lia Levi', '053-9499737', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (343, 'Alon Malka', '051-3129631', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (344, 'Ziv Katz', '051-6541506', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (345, 'Michal Shalom', '053-1001965', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (346, 'Roi Shalom', '052-1296160', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (347, 'Miri Alon', '057-3476472', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (348, 'Ariel Levi', '053-7922128', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (349, 'Ido Ohayon', '059-3705913', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (350, 'Elad Mor', '059-4073810', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (351, 'Oren Dahan', '055-6680878', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (352, 'Shai Tzur', '052-5684771', 'HVAC and Ventilation');
insert into Technician (technician_id, name, phone, specialization) values (353, 'Amit Shapira', '055-5422466', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (354, 'Hila Cohen', '057-4645601', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (355, 'Uri Natan', '055-3969530', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (356, 'Naomi Gabay', '050-5553538', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (357, 'Sivan Israeli', '050-4593816', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (358, 'Tal Israeli', '054-6126053', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (359, 'Ran Cohen', '058-3775392', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (360, 'Gil Russo', '051-2465263', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (361, 'Roni Malka', '059-7942283', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (362, 'Alon Shapira', '058-7273481', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (363, 'Miri Shalom', '050-4841900', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (364, 'Dina Regev', '051-4833970', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (365, 'Yuval Zilberman', '051-5255215', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (366, 'Ofir Levi', '051-3693222', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (367, 'Gal Klein', '056-6229211', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (368, 'Lior Gabay', '053-1769365', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (369, 'Michal Russo', '052-1341315', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (370, 'Liora Shapira', '056-3315893', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (371, 'Maya Alon', '057-6344964', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (372, 'Ofir Malka', '056-7776694', 'HVAC and Ventilation');
insert into Technician (technician_id, name, phone, specialization) values (373, 'Yael Biton', '052-7347201', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (374, 'Omer Tzur', '050-8405405', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (375, 'Paz Jacobi', '058-1048911', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (376, 'Ziv Natan', '059-9694184', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (377, 'Keren Malka', '059-2109308', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (378, 'Uri Cohen', '052-3095985', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (379, 'Alon Tzur', '055-6331848', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (380, 'Lia Alon', '050-2049968', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (381, 'Chen Hadad', '050-9736186', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (382, 'Lia Vaknin', '057-5270953', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (383, 'Ofir Goldstein', '055-3522324', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (384, 'Gil Shapira', '050-3193299', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (385, 'Tomer Tzur', '052-9499503', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (386, 'Nir Dahan', '053-9134813', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (387, 'Alon Gabay', '053-7495434', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (388, 'Dor Levi', '053-9000461', 'HVAC and Ventilation');
insert into Technician (technician_id, name, phone, specialization) values (389, 'Maya Nahum', '050-3887974', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (390, 'Ran Goldstein', '057-6914129', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (391, 'Dina Mor', '055-8111725', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (392, 'Paz Malka', '058-9993205', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (393, 'Ido Levy', '057-3861369', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (394, 'Ido Levy', '052-9944870', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (395, 'Itai Fischer', '056-2675255', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (396, 'Hila Hadad', '058-4408724', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (397, 'Ariel Alon', '055-8216082', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (398, 'Ido Klein', '053-8526108', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (399, 'Ariel Peled', '058-9544813', 'HVAC and Ventilation');
insert into Technician (technician_id, name, phone, specialization) values (400, 'Ariel Jacobi', '058-9420794', 'HVAC and Ventilation');
insert into Technician (technician_id, name, phone, specialization) values (401, 'Chen Levy', '054-1634967', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (402, 'Ofir Gabay', '058-9108337', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (403, 'Lia Peretz', '058-3534133', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (404, 'Maya Chai', '054-7623843', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (405, 'Yuval Alon', '057-7313534', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (406, 'Yael Yosef', '056-7492555', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (407, 'Adam Elimelech', '053-4463152', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (408, 'Yoav Klein', '057-5976482', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (409, 'Amit Shalom', '057-9073355', 'HVAC and Ventilation');
insert into Technician (technician_id, name, phone, specialization) values (410, 'Tomer Mor', '058-8779906', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (411, 'Dina Ohayon', '057-6414537', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (412, 'Naomi Levy', '057-5569459', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (413, 'Ido Oz', '053-8519904', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (414, 'Itai Ohayon', '050-1635802', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (415, 'Shai Peled', '054-7620398', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (416, 'Shira Cohen', '050-1179386', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (417, 'Maya Golan', '052-5664500', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (418, 'Roi Chai', '050-5615051', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (419, 'Lia Fischer', '054-2622580', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (420, 'Eden Tzur', '058-2324626', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (421, 'Ariel Elimelech', '051-3555775', 'HVAC and Ventilation');
insert into Technician (technician_id, name, phone, specialization) values (422, 'Nir Yosef', '058-6562116', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (423, 'Tamar Gabay', '057-4579669', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (424, 'Yoav Vaknin', '057-7175012', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (425, 'Ben Peled', '055-7870974', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (426, 'Tamar Avraham', '053-4929875', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (427, 'Nir Levi', '050-9889924', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (428, 'Roni Dahan', '054-7837564', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (429, 'Sivan Tzur', '054-3518111', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (430, 'Keren Oz', '058-5635632', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (431, 'Tomer Alon', '058-1502851', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (432, 'Ran Shapira', '054-8751065', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (433, 'Tom Biton', '055-9933279', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (434, 'Ruth Peled', '055-9133753', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (435, 'Amit Oz', '051-1532505', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (436, 'Sivan Hadad', '058-1371345', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (437, 'Tomer Ohayon', '050-5954095', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (438, 'Lior Ben-David', '055-3191881', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (439, 'Dina Biton', '058-5926783', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (440, 'Yael Ohayon', '059-6557333', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (441, 'Shira Haim', '054-8404477', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (442, 'Shai Fischer', '053-7082810', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (443, 'Liora Elimelech', '050-8198593', 'HVAC and Ventilation');
insert into Technician (technician_id, name, phone, specialization) values (444, 'Ran Haim', '057-3235326', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (445, 'Miri Ohayon', '059-8545791', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (446, 'Paz Gabay', '056-8360446', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (447, 'Elad Alon', '059-8446410', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (448, 'Shira Dahan', '054-9528639', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (449, 'Alon Malka', '057-9290995', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (450, 'Ben Shapira', '059-3298305', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (451, 'Roni Oz', '053-5693485', 'HVAC and Ventilation');
insert into Technician (technician_id, name, phone, specialization) values (452, 'Maya Yosef', '051-7868512', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (453, 'Lior Klein', '051-5054465', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (454, 'Ariel Mor', '056-4675994', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (455, 'Paz Nahum', '051-3729789', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (456, 'Chen Klein', '059-2127107', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (457, 'Roni Goldstein', '052-4974572', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (458, 'Lia Tzur', '054-9232162', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (459, 'Yuval Shapira', '057-6432514', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (460, 'Nir Ben-David', '051-4312417', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (461, 'Naomi Mor', '053-3311609', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (462, 'Adam Levy', '053-3812087', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (463, 'Lia Klein', '056-1090545', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (464, 'Shira Shapira', '056-4529177', 'HVAC and Ventilation');
insert into Technician (technician_id, name, phone, specialization) values (465, 'Alon Yosef', '058-6398081', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (466, 'Ido Levi', '056-6033357', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (467, 'Ofir Bar', '057-7800012', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (468, 'Dor Levy', '052-6521869', 'Cooking Equipment');
insert into Technician (technician_id, name, phone, specialization) values (469, 'Ariel Peretz', '054-5192100', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (470, 'Dor Shapira', '055-6958114', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (471, 'Dan Elimelech', '055-9825521', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (472, 'Oren Katz', '053-8430344', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (473, 'Yael Zilberman', '052-5451787', 'HVAC and Ventilation');
insert into Technician (technician_id, name, phone, specialization) values (474, 'Naomi Peled', '056-1189117', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (475, 'Adam Jacobi', '059-8738934', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (476, 'Tal Mor', '058-3794426', 'Exhaust Systems');
insert into Technician (technician_id, name, phone, specialization) values (477, 'Lior Malka', '051-3061424', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (478, 'Itai Alon', '050-4840522', 'Dishwashing Systems');
insert into Technician (technician_id, name, phone, specialization) values (479, 'Ido Chai', '055-1772398', 'Electronics and POS');
insert into Technician (technician_id, name, phone, specialization) values (480, 'Yuval Gabay', '052-7364451', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (481, 'Eden Friedman', '059-2798175', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (482, 'Ofir Azulay', '056-5880636', 'Safety Systems');
insert into Technician (technician_id, name, phone, specialization) values (483, 'Yael Chai', '051-9064714', 'Fire Safety Equipment');
insert into Technician (technician_id, name, phone, specialization) values (484, 'Ido Azulay', '051-7357856', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (485, 'Dan Regev', '059-4851608', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (486, 'Chen Ben-David', '055-6592616', 'General Maintenance');
insert into Technician (technician_id, name, phone, specialization) values (487, 'Lia Bar', '056-3487295', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (488, 'Ran Tzur', '053-7991339', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (489, 'Tomer Avraham', '054-9362514', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (490, 'Maya Biton', '057-5774211', 'Refrigeration Systems');
insert into Technician (technician_id, name, phone, specialization) values (491, 'Paz Mor', '051-1265834', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (492, 'Shai Peled', '050-3332535', 'Electrical Systems');
insert into Technician (technician_id, name, phone, specialization) values (493, 'Dan Zilberman', '050-8181721', 'Food Prep Machinery');
insert into Technician (technician_id, name, phone, specialization) values (494, 'Chen Jacobi', '050-3793128', 'Gas Systems');
insert into Technician (technician_id, name, phone, specialization) values (495, 'Omer Nahum', '058-2830898', 'Plumbing');
insert into Technician (technician_id, name, phone, specialization) values (496, 'Dor Yosef', '057-6112118', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (497, 'Dan Azulay', '052-8649882', 'HVAC and Ventilation');
insert into Technician (technician_id, name, phone, specialization) values (498, 'Amit Haim', '058-8262616', 'Kitchen Equipment');
insert into Technician (technician_id, name, phone, specialization) values (499, 'Tom Biton', '050-2540495', 'Beverage Equipment');
insert into Technician (technician_id, name, phone, specialization) values (500, 'Tal Russo', '054-3923547', 'Electronics and POS');
